# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Token-trimmed CLI + MCP server for Forgejo and GitHub"
  homepage "https://github.com/stewartbrothers/gaia"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_darwin_x86_64.tar.gz"
      sha256 "1d2c832f022bae3e72f63ba430f7e7fd7af1d56ef3e391918bd5fee2fa920db8"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
    on_arm do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_darwin_arm64.tar.gz"
      sha256 "4d628fd39917c765e963c6955310fb65d983c63fe90b9a3223b3c9210cae5117"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_linux_x86_64.tar.gz"
        sha256 "c054822ad66f6d46c0f07f7d3d20b8e15a93e620c3dbd18fac66e0e761d2dcf8"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_linux_arm64.tar.gz"
        sha256 "1f81ee8e826221d53d858e1d11df320d6e2e5e38e934c4accfe9913808cec82b"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/gaia", "version"
  end
end
