# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Token-trimmed CLI + MCP server for Forgejo and GitHub"
  homepage "https://github.com/stewartbrothers/gaia"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_darwin_x86_64.tar.gz"
      sha256 "5fa4e704f4d3080b6cd917af2c033e2d70ff502403e9053c4479abb1e8395eef"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
    on_arm do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_darwin_arm64.tar.gz"
      sha256 "0c4f9d15b003f37208f0175a3aa43970d83dd1277f6dae274bf505ef1832dbf5"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_linux_x86_64.tar.gz"
        sha256 "a5fa381340c598f21a5ac63102f61eb386f0eea2645a232b8a84ded8668330ce"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.7.0/gaia_v0.7.0_linux_arm64.tar.gz"
        sha256 "f4b88688b8b5cdb06814737e7c9aed25808a36f82cc47509e2ee190e32d7bd52"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/gaia", "version"
  end
end
